const MakesList = [
  { 1: 'Aspark' },
  { 2: 'Audi' },
  { 3: 'BMW' },
  { 4: 'Bollinger' },
  { 5: 'Buick' },
  { 6: 'Byton' },
  { 7: 'Cadillac' },
  { 8: 'Canoo' },
  { 9: 'Chevrolet' },
  { 10: 'Faraday Future' },
  { 11: 'Fisker' },
  { 12: 'Ford' },
  { 13: 'Genesis' },
  { 14: 'GMC' },
  { 15: 'Honda' },
  { 16: 'Hyundai/Ioniq' },
  { 17: 'Jaguar' },
  { 18: 'Kia' },
  { 19: 'Lexus' },
  { 20: 'Lotus' },
  { 21: 'Lucid' },
  { 22: 'Maserati' },
  { 23: 'Mazda' },
  { 24: 'Mercedes-Benz' },
  { 25: 'Mini' },
  { 26: 'Nissan' },
  { 27: 'Pininfarina' },
  { 28: 'Polestar' },
  { 29: 'Porsche' },
  { 30: 'Rimac' },
  { 31: 'Rivian' },
  { 32: 'Tesla' },
  { 33: 'Volkswagen' },
  { 34: 'Volvo' },
];

export { MakesList };
